package AdditionApp;


/**
* AdditionApp/Addition.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addition.idl
* Wednesday, 24 April, 2024 3:21:29 PM IST
*/

public interface Addition extends AdditionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Addition
