package FactorialApp;


/**
* FactorialApp/Factorial.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Factorial.idl
* Wednesday, 24 April, 2024 10:07:57 PM IST
*/

public interface Factorial extends FactorialOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Factorial
