package FactorialApp;


/**
* FactorialApp/FactorialOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Factorial.idl
* Wednesday, 24 April, 2024 10:07:57 PM IST
*/

public interface FactorialOperations 
{
  double factorial (double n);
} // interface FactorialOperations
